name: inductor

on:
  schedule:
    - cron: 0 16 * * 2,4
  workflow_dispatch:
    inputs:
      training:
        description: Run training?
        required: false
        type: boolean
        default: true
      inference:
        description: Run inference?
        required: false
        type: boolean
        default: false
      default:
        description: Run inductor_default?
        required: false
        type: boolean
        default: true
      dynamic:
        description: Run inductor_dynamic_shapes?
        required: false
        type: boolean
        default: true
      cudagraphs:
        description: Run inductor_cudagraphs?
        required: false
        type: boolean
        default: true
      maxautotune:
        description: Run inductor_max_autotune?
        required: false
        type: boolean
        default: true

concurrency:
  group: jiuding-test
  cancel-in-progress: true

permissions: read-all

jobs:
  linux-focal-cuda12_1-py3_10-gcc9-inductor-build:
    name: cuda12.1-py3.10-gcc9-sm80
    uses: ./.github/workflows/_build.yml
    with:
      build-environment: linux-focal-cuda12.1-py3.10-gcc9-sm80
      cuda-arch-list: '8.0'
      test-matrix: |
        { include: [
          { config: "inductor", shard: 1, num_shards: 1, runner: "self-hosted" },
          { config: "inductor_huggingface", shard: 1, num_shards: 1, runner: "self-hosted" },
          { config: "dynamic_inductor_huggingface", shard: 1, num_shards: 1, runner: "self-hosted" },
          { config: "dynamic_inductor_timm", shard: 1, num_shards: 1, runner: "self-hosted" },
          { config: "dynamic_inductor_torchbench", shard: 1, num_shards: 1, runner: "self-hosted" },
          { config: "aot_inductor_huggingface", shard: 1, num_shards: 1, runner: "self-hosted" },
          { config: "aot_inductor_timm", shard: 1, num_shards: 1, runner: "self-hosted" },
          { config: "aot_inductor_torchbench", shard: 1, num_shards: 1, runner: "self-hosted" },
        ]}
    secrets:
      HUGGING_FACE_HUB_TOKEN: ${{ secrets.HUGGING_FACE_HUB_TOKEN }}

  linux-focal-cuda12_1-py3_10-gcc9-inductor-test:
    name: cuda12.1-py3.10-gcc9-sm80
    uses: ./.github/workflows/_linux-test.yml
    needs: linux-focal-cuda12_1-py3_10-gcc9-inductor-build
    with:
      build-environment: linux-focal-cuda12.1-py3.10-gcc9-sm80
      test-matrix: ${{ needs.linux-focal-cuda12_1-py3_10-gcc9-inductor-build.outputs.test-matrix }}
    secrets:
      HUGGING_FACE_HUB_TOKEN: ${{ secrets.HUGGING_FACE_HUB_TOKEN }}


